# Generated by Django 3.2.18 on 2023-04-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('proof_of_identification', models.FileField(upload_to='proof_of_identification/')),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('permanent_address_street1', models.CharField(max_length=100)),
                ('permanent_address_city', models.CharField(max_length=50)),
                ('permanent_address_state', models.CharField(max_length=50)),
                ('permanent_address_pincode', models.CharField(max_length=10)),
                ('current_address_street1', models.CharField(max_length=100)),
                ('current_address_city', models.CharField(max_length=50)),
                ('current_address_state', models.CharField(max_length=50)),
                ('current_address_pincode', models.CharField(max_length=10)),
                ('joining_date', models.DateField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('Boards', 'Boards')], max_length=20)),
                ('institution_name', models.CharField(max_length=100)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
            options={
                'ordering': ['-year_of_passing'],
            },
        ),
    ]
