# Generated by Django 3.2.18 on 2023-04-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='system_config/')),
                ('company_name', models.CharField(max_length=100)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_port', models.IntegerField()),
                ('smtp_username', models.CharField(max_length=100)),
                ('smtp_password', models.CharField(max_length=100)),
                ('hr_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
            ],
        ),
    ]
