# Generated by Django 3.2.18 on 2023-04-14 06:16

from django.db import migrations

from django.db import migrations
from datetime import date

def add_holidays_2023(apps, schema_editor):
    Holiday = apps.get_model('Employee', 'Holiday')
    month_dict = {
        'January': 1,
        'February': 2,
        'March': 3,
        'April': 4,
        'May': 5,
        'June': 6,
        'July': 7,
        'August': 8,
        'September': 9,
        'October': 10,
        'November': 11,
        'December': 12,
    }
    data = [
        {'month': 'January', 'day': 1, 'name': 'New Year\'s Day'},
        {'month': 'January', 'day': 14, 'name': 'Makar Sankranti'},
        {'month': 'January', 'day': 26, 'name': 'Republic Day'},
        {'month': 'February', 'day': 21, 'name': 'Maha Shivaratri'},
        {'month': 'March', 'day': 20, 'name': 'Holi'},
        {'month': 'April', 'day': 2, 'name': 'Good Friday'},
        {'month': 'April', 'day': 14, 'name': 'Ambedkar Jayanti'},
        {'month': 'April', 'day': 15, 'name': 'Bengali New Year'},
        {'month': 'April', 'day': 21, 'name': 'Ram Navami'},
        {'month': 'April', 'day': 29, 'name': 'Akshaya Tritiya'},
        {'month': 'May', 'day': 1, 'name': 'May Day'},
        {'month': 'May', 'day': 10, 'name': 'Buddha Purnima'},
        {'month': 'July', 'day': 12, 'name': 'Rath Yatra'},
        {'month': 'August', 'day': 15, 'name': 'Independence Day'},
        {'month': 'August', 'day': 19, 'name': 'Muharram'},
        {'month': 'August', 'day': 21, 'name': 'Onam'},
        {'month': 'September', 'day': 10, 'name': 'Ganesh Chaturthi'},
        {'month': 'October', 'day': 2, 'name': 'Gandhi Jayanti'},
        {'month': 'October', 'day': 6, 'name': 'Dussehra'},
        {'month': 'October', 'day': 20, 'name': 'Diwali'},
        {'month': 'November', 'day': 4, 'name': 'Guru Nanak Jayanti'},
        {'month': 'November', 'day': 10, 'name': 'Chhath Puja'},
        {'month': 'November', 'day': 24, 'name': 'Thanksgiving Day'},
        {'month': 'December', 'day': 25, 'name': 'Christmas Day'},
    ]

    for holiday in data:
        dt = date(2023, month_dict[holiday['month']], int(holiday['day']))
        Holiday





class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_holiday'),
    ]

    operations = [
        migrations.RunPython(add_holidays_2023),
    ]



# class Migration(migrations.Migration):

#     dependencies = [
#         ('Employee', '0003_holiday'),
#     ]

#     operations = [
#     ]
